### ISSUE TITLE
React Project Setup

### ISSUE THREAD

**Issue by skabeo** [MussieTeka/space-travelers-hub#25]
We have set up a GitHub project board for our The Space Travelers Hub project and assigned tasks to our team members. You can find the project board at the following link: [Kanban](https://github.com/MussieTeka/space-travelers-hub/projects/1)

Our team consists of two members, and we have assigned tasks to ensure fair time estimate distribution.

Team members:

- @skabeo 
- @MussieTeka 

Please review our project board set up to ensure that everything is in order and that we have correctly followed the instructions provided in the curriculum.

Thank you for your time and feedback.

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- good job including all the cards

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
